### PR TITLE
Private Groups handling

### PR DESCRIPTION
**Pull request by cesarandreslopez**
Ability to get private room (group) history, info and listings. Updated README to show the available
calls. Can send messages to both private groups and public channels.

### CODE REVIEW

**Comment by dstegelman** [comment]
Thanks for the PR.  I will get this reviewed and merged tonight.

**Comment by jadolg** [comment]
this functions have already being implemented on the main project

**Comment by dstegelman** [comment]
These are different calls.  The current ones are using channels ```channel.info, channel.history```.  These methods are using groups.

@cesarandreslopez one change, can you put these in a ```calls.groups``` module instead of ```calls.channel```?  That would help make them distinct as they are a separate object within the [Rocket chat API](https://rocket.chat/docs/developer-guides/rest-api/groups).

If you can make that change, I can get this merged in.

**Comment by cesarandreslopez** [comment]
Fair enough @dstegelman. Will PR in a bit

**Comment by cesarandreslopez** [comment]
Ok @dstegelman maybe this is better?

**Comment by jadolg** [comment]
Sorry I mixed projects :(
My bad

**Comment by dstegelman** [comment]
Released in [1.2.2](https://github.com/dstegelman/rocket-python/releases/tag/1.2.2)

**Pull request merged**
