### PR TITLE
implemented basic channel history endpoint

### PR DESCRIPTION
**Pull request by jadolg**

### CODE REVIEW

**Comment by dstegelman** [comment]
Hi, thanks for the contribution.  Once it can pass pep8 on travis, we can get it merged.

**Comment by jadolg** [comment]
Sorry I'm on this really slow internet connection and I'm not able to see the travis log. Can you please paste it here?

**Comment by dstegelman** [comment]
Travis Output
```
―――――――――――――――――――――――――――――――――― PEP8-check ――――――――――――――――――――――――――――――――――
/home/travis/build/dstegelman/rocket-python/rocketchat/api.py:46:47: E251 unexpected spaces around keyword / parameter equals
    def get_room_history(self, room_id, oldest = None,**kwargs):
                                              ^
/home/travis/build/dstegelman/rocket-python/rocketchat/api.py:46:49: E251 unexpected spaces around keyword / parameter equals
    def get_room_history(self, room_id, oldest = None,**kwargs):
                                                ^
/home/travis/build/dstegelman/rocket-python/rocketchat/api.py:46:54: E231 missing whitespace after ','
    def get_room_history(self, room_id, oldest = None,**kwargs):
                                                     ^
/home/travis/build/dstegelman/rocket-python/rocketchat/api.py:60:1: W293 blank line contains whitespace
^
/home/travis/build/dstegelman/rocket-python/rocketchat/api.py:61:5: E303 too many blank lines (2)
    def get_my_info(self, **kwargs):
```

You can also generate the same by loading and executing the tests locally:

```
py.test tests rocketchat
```

**Comment by jadolg** [comment]
thanks. testing is not working properly on my system :( and my bandwith is very poor.
I'll try to fix it in order to keep my contributions going. I like Rocket.Chat and liked your lib a lot. I started developing a bot for my community chatroom using it.

**Comment by dstegelman** [comment]
Looks good.

**Comment by dstegelman** [comment]
Released in 1.2.1

**Pull request merged**
