### PR TITLE
added options to the get room history

### PR DESCRIPTION
**Pull request by StielEiche**
Needed for a project the latest option of the Rocketchat api and used the case to add all missing features. Couldn't verifiy if the "unreads" option works.

### CODE REVIEW

**Comment by dstegelman** [comment]
Hello and thanks for your contribution @StielEiche .  

Have you tested the implementation to make sure it works?   I no longer have a real-world server setup to test the APIs.  The only thing that makes me slightly nervous is the handling of ```oldest```.

**Comment by StielEiche** [comment]
`inclusive` and `unreads` doesn't produce an error nor do they return something, the rest works as intended. I'm not sure why these two don't have an effect. `oldest` works just normal. I removed the if-else block because your code never used the else part. I wrote you an E-mail with the information for a server where you can test the changes.

**Comment by dstegelman** [comment]
@StielEiche Thanks!

**Comment by dstegelman** [comment]
Released in 1.2.3

**Pull request merged**
